// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type Message struct {
	ID              int64  `json:"id"`
	Room            string `json:"room"`
	Nick            string `json:"nick"`
	Original        string `json:"original"`
	SourceLanguage  string `json:"source_language"`
	WireLanguage    string `json:"wire_language"`
	Service         int64  `json:"service"`
	CreatedAt       int64  `json:"created_at"`
	SenderUserID    int64  `json:"sender_user_id"`
	SenderRequestID string `json:"sender_request_id"`
}

type Observer struct {
	ID              int64  `json:"id"`
	Nick            string `json:"nick"`
	IdentityKeys    []byte `json:"identity_keys"`
	IdentityAddress string `json:"identity_address"`
}

type SendRequest struct {
	UserID        int64  `json:"user_id"`
	RequestID     string `json:"request_id"`
	State         string `json:"state"`
	MessageID     int64  `json:"message_id"`
	Room          string `json:"room"`
	Nick          string `json:"nick"`
	Original      string `json:"original"`
	WireText      string `json:"wire_text"`
	CreatedAt     int64  `json:"created_at"`
	EchoConsumed  int64  `json:"echo_consumed"`
	OriginalMode  int64  `json:"original_mode"`
	ErrorCode     string `json:"error_code"`
	UpdatedAt     int64  `json:"updated_at"`
	ExpiresAt     int64  `json:"expires_at"`
	PayloadPurged int64  `json:"payload_purged"`
}

type Session struct {
	TokenHash []byte `json:"token_hash"`
	UserID    int64  `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
}

type Translation struct {
	CacheKey   string `json:"cache_key"`
	Translated string `json:"translated"`
	CreatedAt  int64  `json:"created_at"`
}

type User struct {
	ID              int64  `json:"id"`
	Email           string `json:"email"`
	Nick            string `json:"nick"`
	PasswordSalt    []byte `json:"password_salt"`
	PasswordHash    []byte `json:"password_hash"`
	IrcPassword     []byte `json:"irc_password"`
	IdentityKeys    []byte `json:"identity_keys"`
	IdentityAddress string `json:"identity_address"`
	IrcRegistered   int64  `json:"irc_registered"`
	CreatedAt       int64  `json:"created_at"`
}
