// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const addMessage = `-- name: AddMessage :one
INSERT INTO messages (room,nick,original,service,created_at,sender_user_id,sender_request_id) VALUES (?,?,?,?,?,?,?) RETURNING id, room, nick, original, service, created_at, sender_user_id, sender_request_id
`

type AddMessageParams struct {
	Room            string `json:"room"`
	Nick            string `json:"nick"`
	Original        string `json:"original"`
	Service         int64  `json:"service"`
	CreatedAt       int64  `json:"created_at"`
	SenderUserID    int64  `json:"sender_user_id"`
	SenderRequestID string `json:"sender_request_id"`
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, addMessage,
		arg.Room,
		arg.Nick,
		arg.Original,
		arg.Service,
		arg.CreatedAt,
		arg.SenderUserID,
		arg.SenderRequestID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Room,
		&i.Nick,
		&i.Original,
		&i.Service,
		&i.CreatedAt,
		&i.SenderUserID,
		&i.SenderRequestID,
	)
	return i, err
}

const backupObserverIdentityPool = `-- name: BackupObserverIdentityPool :one
SELECT identity_pool FROM observer WHERE id = 1
`

func (q *Queries) BackupObserverIdentityPool(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, backupObserverIdentityPool)
	var identity_pool []byte
	err := row.Scan(&identity_pool)
	return identity_pool, err
}

const backupObserverSecrets = `-- name: BackupObserverSecrets :one
SELECT identity_keys FROM observer WHERE id = 1
`

func (q *Queries) BackupObserverSecrets(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, backupObserverSecrets)
	var identity_keys []byte
	err := row.Scan(&identity_keys)
	return identity_keys, err
}

const backupUserIdentityPools = `-- name: BackupUserIdentityPools :many
SELECT id,email,identity_pool FROM users WHERE id > ? ORDER BY id LIMIT 100
`

type BackupUserIdentityPoolsRow struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	IdentityPool []byte `json:"identity_pool"`
}

func (q *Queries) BackupUserIdentityPools(ctx context.Context, id int64) ([]BackupUserIdentityPoolsRow, error) {
	rows, err := q.db.QueryContext(ctx, backupUserIdentityPools, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupUserIdentityPoolsRow{}
	for rows.Next() {
		var i BackupUserIdentityPoolsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.IdentityPool); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backupUserSecrets = `-- name: BackupUserSecrets :many
SELECT id,email,irc_password,identity_keys FROM users WHERE id > ? ORDER BY id LIMIT 100
`

type BackupUserSecretsRow struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	IrcPassword  []byte `json:"irc_password"`
	IdentityKeys []byte `json:"identity_keys"`
}

func (q *Queries) BackupUserSecrets(ctx context.Context, id int64) ([]BackupUserSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, backupUserSecrets, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupUserSecretsRow{}
	for rows.Next() {
		var i BackupUserSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IrcPassword,
			&i.IdentityKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boundReadCursor = `-- name: BoundReadCursor :one
SELECT CAST(COALESCE(MAX(id),0) AS INTEGER) FROM messages WHERE room = ? AND id <= ?
`

type BoundReadCursorParams struct {
	Room string `json:"room"`
	ID   int64  `json:"id"`
}

func (q *Queries) BoundReadCursor(ctx context.Context, arg BoundReadCursorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, boundReadCursor, arg.Room, arg.ID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const cachedTranslation = `-- name: CachedTranslation :one
SELECT translated FROM translations WHERE cache_key = ?
`

func (q *Queries) CachedTranslation(ctx context.Context, cacheKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, cachedTranslation, cacheKey)
	var translated string
	err := row.Scan(&translated)
	return translated, err
}

const claimSend = `-- name: ClaimSend :execrows
INSERT INTO send_requests (user_id,request_id,room,nick,original,original_mode,state,created_at,updated_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING
`

type ClaimSendParams struct {
	UserID       int64  `json:"user_id"`
	RequestID    string `json:"request_id"`
	Room         string `json:"room"`
	Nick         string `json:"nick"`
	Original     string `json:"original"`
	OriginalMode int64  `json:"original_mode"`
	State        string `json:"state"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
	ExpiresAt    int64  `json:"expires_at"`
}

func (q *Queries) ClaimSend(ctx context.Context, arg ClaimSendParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimSend,
		arg.UserID,
		arg.RequestID,
		arg.Room,
		arg.Nick,
		arg.Original,
		arg.OriginalMode,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeEcho = `-- name: ConsumeEcho :one
UPDATE send_requests SET echo_consumed = 1, message_id = ?, state = 'confirmed', error_code = '', updated_at = ? WHERE user_id = ? AND request_id = ? RETURNING user_id, request_id, state, message_id, room, nick, original, wire_text, created_at, echo_consumed, original_mode, error_code, updated_at, expires_at, payload_purged
`

type ConsumeEchoParams struct {
	MessageID int64  `json:"message_id"`
	UpdatedAt int64  `json:"updated_at"`
	UserID    int64  `json:"user_id"`
	RequestID string `json:"request_id"`
}

func (q *Queries) ConsumeEcho(ctx context.Context, arg ConsumeEchoParams) (SendRequest, error) {
	row := q.db.QueryRowContext(ctx, consumeEcho,
		arg.MessageID,
		arg.UpdatedAt,
		arg.UserID,
		arg.RequestID,
	)
	var i SendRequest
	err := row.Scan(
		&i.UserID,
		&i.RequestID,
		&i.State,
		&i.MessageID,
		&i.Room,
		&i.Nick,
		&i.Original,
		&i.WireText,
		&i.CreatedAt,
		&i.EchoConsumed,
		&i.OriginalMode,
		&i.ErrorCode,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PayloadPurged,
	)
	return i, err
}

const createObserver = `-- name: CreateObserver :exec
INSERT INTO observer (id,nick,identity_keys,identity_address) VALUES (1,?,?,?) ON CONFLICT(id) DO NOTHING
`

type CreateObserverParams struct {
	Nick            string `json:"nick"`
	IdentityKeys    []byte `json:"identity_keys"`
	IdentityAddress string `json:"identity_address"`
}

func (q *Queries) CreateObserver(ctx context.Context, arg CreateObserverParams) error {
	_, err := q.db.ExecContext(ctx, createObserver, arg.Nick, arg.IdentityKeys, arg.IdentityAddress)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,?)
`

type CreateSessionParams struct {
	TokenHash []byte `json:"token_hash"`
	UserID    int64  `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email,nick,password_salt,password_hash,irc_password,identity_keys,identity_address,created_at) VALUES (?,?,?,?,?,?,?,?) RETURNING id, email, nick, password_salt, password_hash, irc_password, identity_keys, identity_address, identity_pool, irc_registered, created_at
`

type CreateUserParams struct {
	Email           string `json:"email"`
	Nick            string `json:"nick"`
	PasswordSalt    []byte `json:"password_salt"`
	PasswordHash    []byte `json:"password_hash"`
	IrcPassword     []byte `json:"irc_password"`
	IdentityKeys    []byte `json:"identity_keys"`
	IdentityAddress string `json:"identity_address"`
	CreatedAt       int64  `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Nick,
		arg.PasswordSalt,
		arg.PasswordHash,
		arg.IrcPassword,
		arg.IdentityKeys,
		arg.IdentityAddress,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nick,
		&i.PasswordSalt,
		&i.PasswordHash,
		&i.IrcPassword,
		&i.IdentityKeys,
		&i.IdentityAddress,
		&i.IdentityPool,
		&i.IrcRegistered,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const expireEchoes = `-- name: ExpireEchoes :many
UPDATE send_requests SET state = 'unconfirmed', error_code = 'echo_timeout', updated_at = ? WHERE state = 'awaiting_echo' AND expires_at <= ? RETURNING user_id, request_id, state, message_id, room, nick, original, wire_text, created_at, echo_consumed, original_mode, error_code, updated_at, expires_at, payload_purged
`

type ExpireEchoesParams struct {
	UpdatedAt int64 `json:"updated_at"`
	ExpiresAt int64 `json:"expires_at"`
}

func (q *Queries) ExpireEchoes(ctx context.Context, arg ExpireEchoesParams) ([]SendRequest, error) {
	rows, err := q.db.QueryContext(ctx, expireEchoes, arg.UpdatedAt, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SendRequest{}
	for rows.Next() {
		var i SendRequest
		if err := rows.Scan(
			&i.UserID,
			&i.RequestID,
			&i.State,
			&i.MessageID,
			&i.Room,
			&i.Nick,
			&i.Original,
			&i.WireText,
			&i.CreatedAt,
			&i.EchoConsumed,
			&i.OriginalMode,
			&i.ErrorCode,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.PayloadPurged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishSend = `-- name: FinishSend :one
UPDATE send_requests SET state = ?, error_code = ?, updated_at = ?, expires_at = ? WHERE user_id = ? AND request_id = ? AND state IN ('translating','sending') RETURNING user_id, request_id, state, message_id, room, nick, original, wire_text, created_at, echo_consumed, original_mode, error_code, updated_at, expires_at, payload_purged
`

type FinishSendParams struct {
	State     string `json:"state"`
	ErrorCode string `json:"error_code"`
	UpdatedAt int64  `json:"updated_at"`
	ExpiresAt int64  `json:"expires_at"`
	UserID    int64  `json:"user_id"`
	RequestID string `json:"request_id"`
}

func (q *Queries) FinishSend(ctx context.Context, arg FinishSendParams) (SendRequest, error) {
	row := q.db.QueryRowContext(ctx, finishSend,
		arg.State,
		arg.ErrorCode,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.UserID,
		arg.RequestID,
	)
	var i SendRequest
	err := row.Scan(
		&i.UserID,
		&i.RequestID,
		&i.State,
		&i.MessageID,
		&i.Room,
		&i.Nick,
		&i.Original,
		&i.WireText,
		&i.CreatedAt,
		&i.EchoConsumed,
		&i.OriginalMode,
		&i.ErrorCode,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PayloadPurged,
	)
	return i, err
}

const getObserver = `-- name: GetObserver :one
SELECT id, nick, identity_keys, identity_address, identity_pool FROM observer WHERE id = 1
`

func (q *Queries) GetObserver(ctx context.Context) (Observer, error) {
	row := q.db.QueryRowContext(ctx, getObserver)
	var i Observer
	err := row.Scan(
		&i.ID,
		&i.Nick,
		&i.IdentityKeys,
		&i.IdentityAddress,
		&i.IdentityPool,
	)
	return i, err
}

const getSend = `-- name: GetSend :one
SELECT user_id, request_id, state, message_id, room, nick, original, wire_text, created_at, echo_consumed, original_mode, error_code, updated_at, expires_at, payload_purged FROM send_requests WHERE user_id = ? AND request_id = ?
`

type GetSendParams struct {
	UserID    int64  `json:"user_id"`
	RequestID string `json:"request_id"`
}

func (q *Queries) GetSend(ctx context.Context, arg GetSendParams) (SendRequest, error) {
	row := q.db.QueryRowContext(ctx, getSend, arg.UserID, arg.RequestID)
	var i SendRequest
	err := row.Scan(
		&i.UserID,
		&i.RequestID,
		&i.State,
		&i.MessageID,
		&i.Room,
		&i.Nick,
		&i.Original,
		&i.WireText,
		&i.CreatedAt,
		&i.EchoConsumed,
		&i.OriginalMode,
		&i.ErrorCode,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PayloadPurged,
	)
	return i, err
}

const initializeObserverIdentityPool = `-- name: InitializeObserverIdentityPool :one
UPDATE observer SET identity_pool = CASE WHEN length(identity_pool) = 0 THEN ?1 ELSE identity_pool END WHERE id = 1 RETURNING identity_pool
`

func (q *Queries) InitializeObserverIdentityPool(ctx context.Context, identityPool []byte) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, initializeObserverIdentityPool, identityPool)
	var identity_pool []byte
	err := row.Scan(&identity_pool)
	return identity_pool, err
}

const initializeUserIdentityPool = `-- name: InitializeUserIdentityPool :one
UPDATE users SET identity_pool = CASE WHEN length(identity_pool) = 0 THEN ?1 ELSE identity_pool END WHERE id = ?2 RETURNING identity_pool
`

type InitializeUserIdentityPoolParams struct {
	IdentityPool []byte `json:"identity_pool"`
	ID           int64  `json:"id"`
}

func (q *Queries) InitializeUserIdentityPool(ctx context.Context, arg InitializeUserIdentityPoolParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, initializeUserIdentityPool, arg.IdentityPool, arg.ID)
	var identity_pool []byte
	err := row.Scan(&identity_pool)
	return identity_pool, err
}

const latestRoomMessage = `-- name: LatestRoomMessage :one
SELECT CAST(COALESCE(MAX(id),0) AS INTEGER) FROM messages WHERE room = ?
`

func (q *Queries) LatestRoomMessage(ctx context.Context, room string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestRoomMessage, room)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listSends = `-- name: ListSends :many
SELECT user_id, request_id, state, message_id, room, nick, original, wire_text, created_at, echo_consumed, original_mode, error_code, updated_at, expires_at, payload_purged FROM send_requests WHERE user_id = ? AND room = ? AND payload_purged = 0 AND (state = 'confirmed' OR expires_at > ?) ORDER BY created_at DESC,rowid DESC LIMIT 50
`

type ListSendsParams struct {
	UserID    int64  `json:"user_id"`
	Room      string `json:"room"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) ListSends(ctx context.Context, arg ListSendsParams) ([]SendRequest, error) {
	rows, err := q.db.QueryContext(ctx, listSends, arg.UserID, arg.Room, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SendRequest{}
	for rows.Next() {
		var i SendRequest
		if err := rows.Scan(
			&i.UserID,
			&i.RequestID,
			&i.State,
			&i.MessageID,
			&i.Room,
			&i.Nick,
			&i.Original,
			&i.WireText,
			&i.CreatedAt,
			&i.EchoConsumed,
			&i.OriginalMode,
			&i.ErrorCode,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.PayloadPurged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messages = `-- name: Messages :many
SELECT id, room, nick, original, service, created_at, sender_user_id, sender_request_id FROM messages WHERE room = ? AND id < ? ORDER BY id DESC LIMIT 100
`

type MessagesParams struct {
	Room string `json:"room"`
	ID   int64  `json:"id"`
}

func (q *Queries) Messages(ctx context.Context, arg MessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, messages, arg.Room, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Room,
			&i.Nick,
			&i.Original,
			&i.Service,
			&i.CreatedAt,
			&i.SenderUserID,
			&i.SenderRequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingEcho = `-- name: PendingEcho :one
SELECT user_id, request_id, state, message_id, room, nick, original, wire_text, created_at, echo_consumed, original_mode, error_code, updated_at, expires_at, payload_purged FROM send_requests WHERE room = ? AND nick = ? COLLATE NOCASE AND wire_text = ? AND payload_purged = 0 AND echo_consumed = 0 AND state IN ('sending','awaiting_echo','unconfirmed') AND created_at >= ? ORDER BY created_at,rowid LIMIT 1
`

type PendingEchoParams struct {
	Room      string `json:"room"`
	Nick      string `json:"nick"`
	WireText  string `json:"wire_text"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) PendingEcho(ctx context.Context, arg PendingEchoParams) (SendRequest, error) {
	row := q.db.QueryRowContext(ctx, pendingEcho,
		arg.Room,
		arg.Nick,
		arg.WireText,
		arg.CreatedAt,
	)
	var i SendRequest
	err := row.Scan(
		&i.UserID,
		&i.RequestID,
		&i.State,
		&i.MessageID,
		&i.Room,
		&i.Nick,
		&i.Original,
		&i.WireText,
		&i.CreatedAt,
		&i.EchoConsumed,
		&i.OriginalMode,
		&i.ErrorCode,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PayloadPurged,
	)
	return i, err
}

const prepareSend = `-- name: PrepareSend :one
UPDATE send_requests SET wire_text = ?, state = 'sending', updated_at = ? WHERE user_id = ? AND request_id = ? AND state IN ('translating','sending') RETURNING user_id, request_id, state, message_id, room, nick, original, wire_text, created_at, echo_consumed, original_mode, error_code, updated_at, expires_at, payload_purged
`

type PrepareSendParams struct {
	WireText  string `json:"wire_text"`
	UpdatedAt int64  `json:"updated_at"`
	UserID    int64  `json:"user_id"`
	RequestID string `json:"request_id"`
}

func (q *Queries) PrepareSend(ctx context.Context, arg PrepareSendParams) (SendRequest, error) {
	row := q.db.QueryRowContext(ctx, prepareSend,
		arg.WireText,
		arg.UpdatedAt,
		arg.UserID,
		arg.RequestID,
	)
	var i SendRequest
	err := row.Scan(
		&i.UserID,
		&i.RequestID,
		&i.State,
		&i.MessageID,
		&i.Room,
		&i.Nick,
		&i.Original,
		&i.WireText,
		&i.CreatedAt,
		&i.EchoConsumed,
		&i.OriginalMode,
		&i.ErrorCode,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.PayloadPurged,
	)
	return i, err
}

const pruneMessagesBatch = `-- name: PruneMessagesBatch :execrows
DELETE FROM messages WHERE id IN (SELECT m.id FROM messages AS m WHERE m.created_at < ? ORDER BY m.created_at LIMIT ?)
`

type PruneMessagesBatchParams struct {
	CreatedAt int64 `json:"created_at"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) PruneMessagesBatch(ctx context.Context, arg PruneMessagesBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneMessagesBatch, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneSessions = `-- name: PruneSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) PruneSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneSessions, expiresAt)
	return err
}

const pruneTranslationsBatch = `-- name: PruneTranslationsBatch :execrows
DELETE FROM translations WHERE cache_key IN (SELECT t.cache_key FROM translations AS t WHERE t.created_at < ? ORDER BY t.created_at LIMIT ?)
`

type PruneTranslationsBatchParams struct {
	CreatedAt int64 `json:"created_at"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) PruneTranslationsBatch(ctx context.Context, arg PruneTranslationsBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneTranslationsBatch, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeSendPayloadsBatch = `-- name: PurgeSendPayloadsBatch :execrows
UPDATE send_requests SET payload_purged = 1, room = '', nick = '', original = '', wire_text = '' WHERE rowid IN (SELECT s.rowid FROM send_requests AS s WHERE s.payload_purged = 0 AND s.state IN ('confirmed','failed','unconfirmed') AND s.updated_at < ? AND s.created_at < ? ORDER BY s.updated_at LIMIT ?)
`

type PurgeSendPayloadsBatchParams struct {
	UpdatedAt int64 `json:"updated_at"`
	CreatedAt int64 `json:"created_at"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) PurgeSendPayloadsBatch(ctx context.Context, arg PurgeSendPayloadsBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSendPayloadsBatch, arg.UpdatedAt, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recoverSends = `-- name: RecoverSends :exec
UPDATE send_requests SET state = CASE WHEN state = 'translating' THEN 'failed' ELSE 'unconfirmed' END, error_code = 'interrupted' WHERE state IN ('translating','sending','awaiting_echo')
`

func (q *Queries) RecoverSends(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverSends)
	return err
}

const registerIRC = `-- name: RegisterIRC :exec
UPDATE users SET irc_registered = 1 WHERE id = ?
`

func (q *Queries) RegisterIRC(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, registerIRC, id)
	return err
}

const saveTranslation = `-- name: SaveTranslation :exec
INSERT INTO translations (cache_key,translated,created_at) VALUES (?,?,CAST(unixepoch('subsec') * 1000 AS INTEGER)) ON CONFLICT(cache_key) DO UPDATE SET translated = excluded.translated, created_at = excluded.created_at
`

type SaveTranslationParams struct {
	CacheKey   string `json:"cache_key"`
	Translated string `json:"translated"`
}

func (q *Queries) SaveTranslation(ctx context.Context, arg SaveTranslationParams) error {
	_, err := q.db.ExecContext(ctx, saveTranslation, arg.CacheKey, arg.Translated)
	return err
}

const sessionUser = `-- name: SessionUser :one
SELECT users.id, users.email, users.nick, users.password_salt, users.password_hash, users.irc_password, users.identity_keys, users.identity_address, users.identity_pool, users.irc_registered, users.created_at FROM users JOIN sessions ON users.id = sessions.user_id WHERE sessions.token_hash = ? AND sessions.expires_at > ?
`

type SessionUserParams struct {
	TokenHash []byte `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) SessionUser(ctx context.Context, arg SessionUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, sessionUser, arg.TokenHash, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nick,
		&i.PasswordSalt,
		&i.PasswordHash,
		&i.IrcPassword,
		&i.IdentityKeys,
		&i.IdentityAddress,
		&i.IdentityPool,
		&i.IrcRegistered,
		&i.CreatedAt,
	)
	return i, err
}

const unreadMessages = `-- name: UnreadMessages :one
SELECT COUNT(*) FROM messages WHERE room = ? AND id > ? AND service = 0 AND (sender_user_id = 0 OR sender_user_id != ?)
`

type UnreadMessagesParams struct {
	Room         string `json:"room"`
	ID           int64  `json:"id"`
	SenderUserID int64  `json:"sender_user_id"`
}

func (q *Queries) UnreadMessages(ctx context.Context, arg UnreadMessagesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, unreadMessages, arg.Room, arg.ID, arg.SenderUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, nick, password_salt, password_hash, irc_password, identity_keys, identity_address, identity_pool, irc_registered, created_at FROM users WHERE email = ?
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nick,
		&i.PasswordSalt,
		&i.PasswordHash,
		&i.IrcPassword,
		&i.IdentityKeys,
		&i.IdentityAddress,
		&i.IdentityPool,
		&i.IrcRegistered,
		&i.CreatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, nick, password_salt, password_hash, irc_password, identity_keys, identity_address, identity_pool, irc_registered, created_at FROM users WHERE id = ?
`

func (q *Queries) UserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nick,
		&i.PasswordSalt,
		&i.PasswordHash,
		&i.IrcPassword,
		&i.IdentityKeys,
		&i.IdentityAddress,
		&i.IdentityPool,
		&i.IrcRegistered,
		&i.CreatedAt,
	)
	return i, err
}

const userIdentityPool = `-- name: UserIdentityPool :one
SELECT identity_pool FROM users WHERE id = ?
`

func (q *Queries) UserIdentityPool(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, userIdentityPool, id)
	var identity_pool []byte
	err := row.Scan(&identity_pool)
	return identity_pool, err
}
